name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up QEMU for ARM
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: install Docker
        run: sudo apt update && sudo apt purge containerd* -y && sudo apt install docker.io -y

      - name: run Docker
        run: |
          sudo docker pull --platform linux/arm64 rockylinux:9.3
          sudo docker images
          
      - name: run script
        run: sudo docker run -t rockylinux:9.3 bash -e build_opi_knl.sh && ls build -a