name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install-dep
      run: |
        sudo apt update
        sudo apt install neofetch qt5-default -y

    - name: demo
      run: |
        qmake

    - name: info
      run: neofetch