name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest-arm64
    container:
      image: rockylinux:latest
      options: --privileged
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install-dep
      run: |
        sudo dnf makecache
        suso dnf in fastfetch -y
    - name: info
      run: fastfetch