name: CI
on: [push]
jobs:
  package:
    runs-on: macos-latest
    steps: 
    #- name: Checkout repository
      #uses: actions/checkout@v3

    - name: mount
      run: |
        curl -L https://get.docker.com | sh
