name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: mount
      run: |
        cat /dev/null > /home
        ls /home
        
