name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: clearlinux:latest
      options: --privileged
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install-dep
      run: |
        swupd update
        swupd bundle-add fastfetch dev-utils kde-frameworks5-dev
        swupd search qmake
    - name: info
      run: fastfetch

    - name: qmake
      run: qmake && qmake -v