name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: mount
      run: |
        sudo apt install expect davfs2 -y
        mkdir mirrors
        sudo expect sync.sh
        sudo systemctl daemon-reload
    - name: sync
      run: |
        cd mirrors
        rsync -az rsync://rsync.mirrors.ustc.edu.cn/debian/* debian
        
