name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    container: amontslban/freebsd
    steps: 
    - name: in-dep
      run: |     
        portsnap
    - name: build
      run: |        
        echo none
    - name: info
      run: uname -a
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: /root/
        if-no-files-found: error
        retention-days: 10
