name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: run script
      run: |
        bash build_opi_knl.sh
        ls build -a

    
