name: CI
on: [push]
jobs:
  package:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: mount
      run: |
        sudo apt install expect -y
        mkdir mirrors
        bash sync.sh
    - name: rsync
      run: |
        cd mirrors
        rsync -avz rsync://rsync.ustc.edu.cn/debian/* debian
        
