name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: rockylinux:9.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up QEMU for ARM
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
          
      - name: run script
        run: sudo uname -a && ls && sudo bash -e build_opi_knl.sh && ls build -a